version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: log430
      POSTGRES_PASSWORD: laboratoire
      POSTGRES_DB: log430
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://log430:laboratoire@localhost:5432/log430
    tty: true
    stdin_open: true
  
volumes:
  pgdata:
