name: CI Pipeline

on:
  push:
    branches: [ lab2, main ]
  pull_request:
    branches: [ lab2, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: log430
          POSTGRES_PASSWORD: laboratoire
          POSTGRES_DB: log430
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U log430" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://log430:laboratoire@localhost:5432/log430

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (flake8)
        run: |
          flake8 src/
      - name: Run tests (pytest)
        run: |
          pytest
      - name: Build Docker image (optionnel)
        run: |
          docker build -t pos-app .
